# Generated by Django 3.0.7 on 2020-07-24 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiakas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yritys', models.CharField(max_length=200, null=True)),
                ('tilaaja', models.CharField(blank=True, max_length=200, null=True)),
                ('puhelin', models.CharField(blank=True, max_length=200, null=True)),
                ('sähköposti', models.CharField(blank=True, max_length=200, null=True)),
                ('lisätty', models.DateTimeField(auto_now_add=True, null=True)),
                ('käyttäjä', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Yrityslista',
            },
        ),
        migrations.CreateModel(
            name='Laskutustiedot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yritys', models.CharField(max_length=200, null=True)),
                ('osoite', models.CharField(blank=True, max_length=200, null=True)),
                ('postinumero', models.CharField(blank=True, max_length=10, null=True)),
                ('postitoimipaikka', models.CharField(blank=True, max_length=200, null=True)),
                ('yhteyshenkilö', models.CharField(blank=True, max_length=200, null=True)),
                ('nimike', models.CharField(blank=True, max_length=200, null=True)),
                ('puhelin', models.CharField(blank=True, max_length=200, null=True)),
                ('lisätty', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Laskutustiedot',
            },
        ),
        migrations.CreateModel(
            name='Tilaus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilauspäivä', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('merkinne', models.CharField(blank=True, max_length=200, null=True)),
                ('tila', models.CharField(choices=[('Jonossa', 'Jonossa'), ('Työn alla', 'Työn alla'), ('Valmis', 'Valmis')], max_length=200, null=True)),
                ('työ', models.CharField(choices=[('Asennus', 'Asennus'), ('Huolto', 'Huolto'), ('Koulutus', 'Koulutus'), ('Ohjelmointi', 'Ohjelmointi'), ('Remontti', 'Remontti'), ('Konsultointi', 'Konsultointi'), ('Muu', 'Muu')], max_length=200, null=True)),
                ('luokka', models.CharField(choices=[('Normaali', 'Normaali'), ('Kiireinen', 'Kiireinen'), ('Päivystystyö', 'Päivystystyö')], max_length=200, null=True)),
                ('järjestelmä', models.CharField(choices=[('Rikosilmoitinjärjestelmä', 'Rikosilmoitinjärjestelmä'), ('Videovalvontajärjestelmä', 'Videovalvontajärjestelmä'), ('Kulunvalvontajärjestelmä', 'Kulunvalvontajärjestelmä'), ('Ilmoituksensiirtojärjestelmä', 'Ilmoituksensiirtojärjestelmä'), ('TV-järjestelmä', 'TV-järjestelmä'), ('Äänentoistojärjestelmä', 'Äänentoistojärjestelmä'), ('Kuulutusjärjestelmä', 'Kuulutusjärjestelmä'), ('Ovipuhelinjärjestelmä', 'Ovipuhelinjärjestelmä'), ('Pikapuhelinjärjestelmä', 'Pikapuhelinjärjestelmä'), ('Kiinteistö', 'Kiinteistö'), ('Ovikellojärjestelmä', 'Ovikellojärjestelmä'), ('Sähköjärjestelmä', 'Sähköjärjestelmä'), ('Info-TV järjestelmä', 'Info-TV järjestelmä'), ('Heikkovirtajärjestelmä', 'Heikkovirtajärjestelmä'), ('ATK-järjestelmä', 'ATK-järjestelmä'), ('Korjausrakentaminen', 'Korjausrakentaminen'), ('Tuotesuojajärjestelmä', 'Tuotesuojajärjestelmä'), ('Lukitusjärjestelmä', 'Lukitusjärjestelmä'), ('Kiinteistoautomatiikkajärjestelmä', 'Kiinteistoautomatiikkajärjestelmä'), ('Palovaroitinjärjestelmä', 'Palovaroitinjärjestelmä'), ('Kylmälaite', 'Kylmälaite'), ('Paloilmoitinjärjestelmä', 'Paloilmoitinjärjestelmä'), ('Antennijärjestelmä', 'Antennijärjestelmä'), ('Purunpoistojärjestelmä', 'Purunpoistojärjestelmä'), ('Muu', 'Muu')], max_length=200, null=True)),
                ('kuvaus', models.TextField(blank=True)),
                ('listätieto', models.TextField(blank=True)),
                ('laskutettu', models.CharField(choices=[('Ei', 'Ei'), ('Kyllä', 'Kyllä')], default='Ei', max_length=200)),
                ('asiakas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='käyttäjät.Asiakas')),
                ('laskutustiedot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='käyttäjät.Laskutustiedot')),
            ],
            options={
                'verbose_name_plural': 'tilaukset',
            },
        ),
        migrations.CreateModel(
            name='TyöKohde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kohde', models.CharField(max_length=200, null=True)),
                ('osoite', models.CharField(blank=True, max_length=200, null=True)),
                ('postinumero', models.CharField(blank=True, max_length=10, null=True)),
                ('postitoimipaikka', models.CharField(blank=True, max_length=200, null=True)),
                ('yhteyshenkilö', models.CharField(blank=True, max_length=200, null=True)),
                ('nimike', models.CharField(blank=True, max_length=200, null=True)),
                ('puhelin', models.CharField(blank=True, max_length=200, null=True)),
                ('lisätty', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Työ kohteet',
            },
        ),
        migrations.CreateModel(
            name='Työt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('päiväys', models.DateField(default=django.utils.timezone.now)),
                ('kuvaus', models.TextField(default='-')),
                ('työnimi', models.CharField(max_length=50)),
                ('työtuntia', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('työhinta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lisännyt', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tilausnumero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='käyttäjät.Tilaus')),
            ],
        ),
        migrations.CreateModel(
            name='Tuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuotetunnus', models.CharField(default='tunnus', max_length=40)),
                ('tuotenimike', models.CharField(default='tuote', max_length=200)),
                ('tuotemäärä', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('tuotehinta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('työnumero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='käyttäjät.Työt')),
            ],
            options={
                'verbose_name_plural': 'Lisää tuote',
            },
        ),
        migrations.AddField(
            model_name='tilaus',
            name='työkohde',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='käyttäjät.TyöKohde'),
        ),
    ]
