# Generated by Django 3.0.7 on 2020-07-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('käyttäjät', '0001_initial'),
    ]

    operations = [
	migrations.RunSQL('ALTER SEQUENCE käyttäjät_tilaus_id_seq RESTART WITH 8365;')    

]
