# Generated by Django 3.0.7 on 2020-07-24 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('käyttäjät', '0002_auto_20200724_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuote',
            name='tilausnumero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='käyttäjät.Tilaus'),
        ),
    ]
